FROM node:18-alpine

WORKDIR /app

# Install dependencies
# We copy only package.json first to leverage Docker cache
COPY package*.json ./
RUN npm install

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

EXPOSE 3000

# Run the development server
CMD ["npm", "run", "dev"] 