services:
  statistics-db:
    image: postgres:13-alpine
    container_name: statistics-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: statistics
    ports:
      - "5432:5432"
    volumes:
      - statistics-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: statistics-redis
    ports:
      - "6379:6379"

  statistics-service:
    build:
      context: ./services/statistics-service
      dockerfile: Dockerfile.dev
    container_name: statistics-service
    depends_on:
      - statistics-db
      - redis
    environment:
      DB_HOST: statistics-db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: statistics
      PORT: 3001
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./services/statistics-service:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm run db:migrate && npm run dev"
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "3000:80"
    depends_on:
      - statistics-service
      - frontend

volumes:
  statistics-data: 